/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id:
    "us-east-1:f14fdd73-ef6a-49e6-b154-b6a16d6b2c5a",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_iALWWmcF4",
  aws_user_pools_web_client_id: "49i50g2forsdm3seel0hraj5sq",
  oauth: {},
};
export default awsmobile;
